# Proceso de ETL

### Procesamiento de Datos desde Archivos JSON a CSV
* Para Iniciar este proyecto voy a realizar un procesamiento de datos desde archivos JSON a archivos CSV, abordando la detección de codificaciónes y la conversión de datos. A continuación, se explica cada paso del proceso:

In [43]:
# Importamos las bibliotecas necesarias
import chardet # La utilizamos para detectar la codificación de caracteres en texto
import pandas as pd
import ast # La utilizo para analizar y manipular expresiones y declaraciones
import re # La utilizo para realizar búsquedas y manipulaciones avanzadas de patrones de texto
import json #  La utilizo para trabajar con datos en formato JSON

### Detección de Codificación:

In [2]:
# Con esta función examine el encoding del archivo "australian_user_reviews.json"

def detect_encoding(file_path):
        
    with open(file_path, 'rb') as f:
        result = chardet.detect(f.read())
        return result['encoding']

### Lectura y Procesamiento de "australian_user_reviews.json":

* Detectamos la codificación del archivo "australian_user_reviews.json" y la imprimimos.
Leemos y procesamos los datos en un DataFrame llamado df_reviews.
Guardamos los datos en un archivo CSV llamado "aus_reviews.csv".

In [3]:
# He Determinado la codificación del archivo "australian_user_reviews.json"
file_path = 'australian_user_reviews.json'
encoding = detect_encoding(file_path)

print(f"La codificación del archivo es: {encoding}")

La codificación del archivo es: MacRoman

In [4]:
# Leyendo los datos de "australian_user_reviews.json"

rows = []

with open ('australian_user_reviews.json', encoding='MacRoman') as f:
    for line in f.readlines():
        rows.append(ast.literal_eval(line))

df_reviews = pd.DataFrame(rows)
df_reviews.head()

,user_id,user_url,reviews
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2..."
1,js41637,http://steamcommunity.com/id/js41637,"[{'funny': '', 'posted': 'Posted June 24, 2014..."
2,evcentric,http://steamcommunity.com/id/evcentric,"[{'funny': '', 'posted': 'Posted February 3.',..."
3,doctr,http://steamcommunity.com/id/doctr,"[{'funny': '', 'posted': 'Posted October 14, 2..."
4,maplemage,http://steamcommunity.com/id/maplemage,"[{'funny': '3 people found this review funny',..."

In [5]:
# Guardando el df con la información de "australian_user_reviews.json" en formato CSV
df_reviews.to_csv('aus_reviews.csv', index=False)

### Lectura y Procesamiento de "australian_users_items.json":

* Repetimos el proceso para el archivo "australian_users_items.json", almacenando los datos en df_items y guardándolos en "aus_items.csv".

In [6]:
# Leyendo los datos de "australian_users_items.json" e importarlo.

rows = []

with open ('australian_users_items.json', encoding='MacRoman') as f:
    for line in f.readlines():
        rows.append(ast.literal_eval(line))

df_items = pd.DataFrame(rows)
df_items.head()

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,888,76561198035864385,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest..."
3,Riot-Punch,328,76561197963445855,http://steamcommunity.com/id/Riot-Punch,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
4,doctr,541,76561198002099482,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea..."

In [7]:
# Guardar el df con la información de "australian_users_items.json" en formato CSV
df_items.to_csv('aus_items.csv', index=False)

### Detección de Codificación de "output_steam_games.json":

In [8]:
# Ahora voy a revisar la  codificación del archivo "output_steam_games.json" para importar su contenido

file_path = 'output_steam_games.json'
encoding = detect_encoding(file_path)
print(f"La codificación del archivo es: {encoding}")

La codificación del archivo es: ascii

### Lectura y Procesamiento de "output_steam_games.json":

* Leemos y procesamos los datos en un DataFrame llamado df_games.
Finalmente, guardamos los datos en un archivo CSV llamado "output_games.csv".

In [9]:
# Voy a leer los  datos de "output_steam_games.json" e importarlo a un Dataframe.
df_games = pd.read_json('output_steam_games.json', lines=True)
df_games

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
0,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
1,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
2,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
3,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
4,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120440,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,Colony On Mars,http://store.steampowered.com/app/773640/Colon...,2018-01-04,"[Strategy, Indie, Casual, Simulation]",http://steamcommunity.com/app/773640/reviews/?...,"[Single-player, Steam Achievements]",1.99,0.0,773640.0,"Nikita ""Ghost_RUS"""
120441,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,LOGistICAL: South Africa,http://store.steampowered.com/app/733530/LOGis...,2018-01-04,"[Strategy, Indie, Casual]",http://steamcommunity.com/app/733530/reviews/?...,"[Single-player, Steam Achievements, Steam Clou...",4.99,0.0,733530.0,Sacada
120442,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,2018-01-04,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,0.0,610660.0,Laush Dmitriy Sergeevich
120443,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,2017-09-02,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",4.99,0.0,658870.0,"xropi,stev3ns"
120444,None,None,Maze Run VR,None,http://store.steampowered.com/app/681550/Maze_...,None,"[Early Access, Adventure, Indie, Action, Simul...",http://steamcommunity.com/app/681550/reviews/?...,"[Single-player, Stats, Steam Leaderboards, HTC...",4.99,1.0,681550.0,None

In [10]:
# Ahora procedo a guardarlo con la información de "output_steam_games.json" en formato CSV
df_games.to_csv('output_games.csv', index=False)

* Con el codigo anterior nos centramos en el procesamiento de datos desde archivos JSON a archivos CSV, abordando de manera eficiente los problemas potenciales de codificación y proporcionando una estructura organizada para el procesamiento de datos.

## 1.Leyendo los Datasets

* En esta seccion que he leido mis Dataframes 'df1=aus_reviews.csv' y 'df2=aus_items.csv' ambos archivos contienen
columnas anidadas, voy a proceder a desanidar y guardarlos en un nuevo csv para despues trabajar con mi siguiente paso que es el EDA.

In [2]:
df1= pd.read_csv('aus_reviews.csv')

In [5]:
df1.head()

,user_id,user_url,reviews
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2..."
1,js41637,http://steamcommunity.com/id/js41637,"[{'funny': '', 'posted': 'Posted June 24, 2014..."
2,evcentric,http://steamcommunity.com/id/evcentric,"[{'funny': '', 'posted': 'Posted February 3.',..."
3,doctr,http://steamcommunity.com/id/doctr,"[{'funny': '', 'posted': 'Posted October 14, 2..."
4,maplemage,http://steamcommunity.com/id/maplemage,"[{'funny': '3 people found this review funny',..."

In [10]:
# hago una lectura de mi df en un df copia.
df1 = "aus_reviews.csv"
df1_reviews_copia = pd.read_csv(df1, low_memory=False)

In [12]:
# Hago un .shape solo para observar la estructura del df.
df1_reviews_copia.shape

(25799, 3)

* Como bien hemos visto en los codigos de arriba la columna "reviews" se encuentra anidada, lo que hare ahora es desanidarla.

In [14]:
# Muestro el tipo de dato y el contenido de la celda ubicada en la primera fila de la columna "reviews" 
data1 = df1_reviews_copia.loc[0, "reviews"]
print("tipo dato: ", type(data1),"\n")
print(data1)

# Ahora hago una lista de Python utilizando ast.literal_eval
df1_lista = ast.literal_eval(data1)

# Convierto a un DataFrame 
df1_reviews = pd.DataFrame(df1_lista)
df1_reviews.head(10)

tipo dato:  <class 'str'>

[{'funny': '', 'posted': 'Posted November 5, 2011.', 'last_edited': '', 'item_id': '1250', 'helpful': 'No ratings yet', 'recommend': True, 'review': 'Simple yet with great replayability. In my opinion does "zombie" hordes and team work better than left 4 dead plus has a global leveling system. Alot of down to earth "zombie" splattering fun for the whole family. Amazed this sort of FPS is so rare.'}, {'funny': '', 'posted': 'Posted July 15, 2011.', 'last_edited': '', 'item_id': '22200', 'helpful': 'No ratings yet', 'recommend': True, 'review': "It's unique and worth a playthrough."}, {'funny': '', 'posted': 'Posted April 21, 2011.', 'last_edited': '', 'item_id': '43110', 'helpful': 'No ratings yet', 'recommend': True, 'review': 'Great atmosphere. The gunplay can be a bit chunky at times but at the end of the day this game is definitely worth it and I hope they do a sequel...so buy the game so I get a sequel!'}]

,funny,posted,last_edited,item_id,helpful,recommend,review
0,,"Posted November 5, 2011.",,1250,No ratings yet,True,Simple yet with great replayability. In my opi...
1,,"Posted July 15, 2011.",,22200,No ratings yet,True,It's unique and worth a playthrough.
2,,"Posted April 21, 2011.",,43110,No ratings yet,True,Great atmosphere. The gunplay can be a bit chu...

* Vemos que nuestro nuevo 'df1_reviews' tiene tipo de dato 'str' asi es que lo convertire a 'list'

In [15]:
def convertir_str_list(formato):
    '''
    Funcion para convertir cada registro de formato str a lista.
    Recibe como parámetro un str con formato lista
    '''
    list_registro = ast.literal_eval(formato) # convertir cada registro str a lista
    return list_registro

In [16]:
# saco una copia al df1_reviews_copia y lo convierto los registros a listas

df1_reviews_copia_2 = df1_reviews_copia.copy()
df1_reviews_copia_2['reviews'] = df1_reviews_copia_2['reviews'].apply(convertir_str_list)

* Bueno llego la hora de desanidar la columna 'reviews' finalmente.

In [20]:
# desanidar columna "reviews"

list_complete_dict = []
for indice, fila in df1_reviews_copia_2.iterrows():       # recorrer cada fila del dataframe
    user_id = fila['user_id']                           # guarda cada id de un usuario en una variable "user_id"
    user_url = fila['user_url']
    for dict_item_user in fila['reviews']:              # recorre cada fila de la columna "items"
        dict_item_user['user_id'] = user_id             # agrega una clave al diccionario que contiene el id del usuario
        dict_item_user['user_url'] = user_url
        list_complete_dict.append(dict_item_user)       # agrega cada dict a una lista general

df1_reviews_copia_3 = pd.DataFrame(list_complete_dict)    # crea un dataframe con la lista de dict
orden_columnas = ['user_id', 'user_url', "funny", "posted", "last_edited", 'item_id', 'helpful', 'recommend', 'review']
df1_reviews_copia_3 = df1_reviews_copia_3[orden_columnas]

In [21]:
df1_reviews_copia_3.head() #  Hu-a-la!!! lo he coseguido

,user_id,user_url,funny,posted,last_edited,item_id,helpful,recommend,review
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,,"Posted November 5, 2011.",,1250,No ratings yet,True,Simple yet with great replayability. In my opi...
1,76561197970982479,http://steamcommunity.com/profiles/76561197970...,,"Posted July 15, 2011.",,22200,No ratings yet,True,It's unique and worth a playthrough.
2,76561197970982479,http://steamcommunity.com/profiles/76561197970...,,"Posted April 21, 2011.",,43110,No ratings yet,True,Great atmosphere. The gunplay can be a bit chu...
3,js41637,http://steamcommunity.com/id/js41637,,"Posted June 24, 2014.",,251610,15 of 20 people (75%) found this review helpful,True,I know what you think when you see this title ...
4,js41637,http://steamcommunity.com/id/js41637,,"Posted September 8, 2013.",,227300,0 of 1 people (0%) found this review helpful,True,For a simple (it's actually not all that simpl...

<h3> Ahora voy a desanidar el siguiente "df2=aus_items-csv"</h3>

In [30]:
df2= pd.read_csv('aus_items.csv')

In [31]:
# Leo el df2
df2 = "aus_items.csv"
df2_items_copia = pd.read_csv(df2, low_memory=False)

In [32]:
df2_items_copia.head()

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,888,76561198035864385,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest..."
3,Riot-Punch,328,76561197963445855,http://steamcommunity.com/id/Riot-Punch,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
4,doctr,541,76561198002099482,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea..."

In [33]:
# vemos la estructura de la columna "items"
data2 = df2_items_copia.loc[0, "items"]
print("tipo dato: ", type(data2),"\n")
print(data2)

# Convertir la cadena a una lista
df2_lista = ast.literal_eval(data2)

# Convertir la lista en un DataFrame
df2_items= pd.DataFrame(df2_lista)
df2_items.head(10)

tipo dato:  <class 'str'>


  item_id                  item_name  playtime_forever  playtime_2weeks
0      10             Counter-Strike                 6                0
1      20      Team Fortress Classic                 0                0
2      30              Day of Defeat                 7                0
3      40         Deathmatch Classic                 0                0
4      50  Half-Life: Opposing Force                 0                0
5      60                   Ricochet                 0                0
6      70                  Half-Life                 0                0
7     130      Half-Life: Blue Shift                 0                0
8     300      Day of Defeat: Source              4733                0
9     240     Counter-Strike: Source              1853                0

In [34]:
# A convertir los registros a listas

df2_items_copia_2 = df2_items_copia.copy()
df2_items_copia_2['items'] = df2_items_copia_2['items'].apply(convertir_str_list)

* Ahora el turno de desanidar al "df2=aus_items.csv"

In [35]:
# desanidar columna "item"

list_complete_dict = []
for indice, fila in df2_items_copia_2.iterrows():       
    user_id = fila['user_id']                           
    items_count = fila['items_count']
    steam_id = fila['steam_id']
    user_url = fila['user_url']	
    for dict_item_user in fila['items']:            
        dict_item_user['user_id'] = user_id             
        dict_item_user['items_count'] = items_count
        dict_item_user['steam_id'] = steam_id
        dict_item_user['user_url'] = user_url
        list_complete_dict.append(dict_item_user)      

df2_items_copia_3 = pd.DataFrame(list_complete_dict)    
orden_columnas = ['user_id', "items_count", "steam_id",'user_url', "item_id", "item_name", "playtime_forever", "playtime_2weeks"]
df2_items_copia_3 = df2_items_copia_3[orden_columnas]

In [36]:
df2_items_copia_3.head(5)

,user_id,items_count,steam_id,user_url,item_id,item_name,playtime_forever,playtime_2weeks
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,10,Counter-Strike,6,0
1,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,20,Team Fortress Classic,0,0
2,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,30,Day of Defeat,7,0
3,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,40,Deathmatch Classic,0,0
4,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,50,Half-Life: Opposing Force,0,0

In [41]:
df3 = pd.read_csv('output_games.csv', low_memory=False)

* La siguiente Función revisa el tipo de datos y el  contenido dentro de cada columna así como el porcentaje de nulos y la cantidad de filas que estan toalmente nulas. Al final recibe como parámetro el dataframe a examinar.
Esta función es útil para realizar un análisis rápido de la estructura y calidad de los datos en un DataFrame, lo que puede ser útil en tareas de limpieza y preparación de datos.

In [59]:
# Pondre manos a la obra y revisare el tipo de datos de cada columna

def verificar_tipo_datos(df):
    
    mi_dict = {"nombre_campo": [], "tipo_datos": [], "no_nulos_%": [], "nulos_%": []} # Creo un diccionario para almacenar la información sobre las columnas del DataFrame.

    for columna in df.columns:  # Se recorren las columnas del DataFrame, y se calculan los porcentajes de valores no nulos y nulos para cada columna.
        porcentaje_no_nulos = (df[columna].count() / len(df)) * 100
        mi_dict["nombre_campo"].append(columna)
        mi_dict["tipo_datos"].append(df[columna].apply(type).unique())
        mi_dict["no_nulos_%"].append(round(porcentaje_no_nulos, 2))
        mi_dict["nulos_%"].append(round(100-porcentaje_no_nulos, 2))

    df_info = pd.DataFrame(mi_dict) # A partir de la información recopilada en el diccionario, se crea un nuevo DataFrame

    for columna in df.columns:
        print(columna, " (nulos) = ", df[columna].isnull().sum())
    
    print("\nfilas completamente nulas: ", df.isna().all(axis=1).sum())
    
    return df_info

In [39]:
# Verificando df1_reviews_copia
verificar = verificar_tipo_datos(df1_reviews_copia)

# imprimir la información en la salida
print(verificar)

user_id  (nulos) =  0
user_url  (nulos) =  0
reviews  (nulos) =  0

filas completamente nulas:  0
  nombre_campo       tipo_datos  no_nulos_%  nulos_%
0      user_id  [<class 'str'>]       100.0      0.0
1     user_url  [<class 'str'>]       100.0      0.0
2      reviews  [<class 'str'>]       100.0      0.0

In [40]:
# Verificando df2_itemns_copia2
verificar2 = verificar_tipo_datos(df2_items_copia_3)
print(verificar2)

user_id  (nulos) =  0
items_count  (nulos) =  0
steam_id  (nulos) =  0
user_url  (nulos) =  0
item_id  (nulos) =  0
item_name  (nulos) =  0
playtime_forever  (nulos) =  0
playtime_2weeks  (nulos) =  0

filas completamente nulas:  0
       nombre_campo       tipo_datos  no_nulos_%  nulos_%
0           user_id  [<class 'str'>]       100.0      0.0
1       items_count  [<class 'int'>]       100.0      0.0
2          steam_id  [<class 'int'>]       100.0      0.0
3          user_url  [<class 'str'>]       100.0      0.0
4           item_id  [<class 'str'>]       100.0      0.0
5         item_name  [<class 'str'>]       100.0      0.0
6  playtime_forever  [<class 'int'>]       100.0      0.0
7   playtime_2weeks  [<class 'int'>]       100.0      0.0

In [60]:
# Verificando 'df3=output_games.csv'
verificar3 = verificar_tipo_datos(df3)
print(verificar3)

publisher  (nulos) =  96381
genres  (nulos) =  91593
app_name  (nulos) =  88312
title  (nulos) =  90360
url  (nulos) =  88310
release_date  (nulos) =  90377
tags  (nulos) =  88473
reviews_url  (nulos) =  88312
specs  (nulos) =  88980
price  (nulos) =  89687
early_access  (nulos) =  88310
id  (nulos) =  88312
developer  (nulos) =  91609

filas completamente nulas:  88310
    nombre_campo                        tipo_datos  no_nulos_%  nulos_%
0      publisher  [<class 'float'>, <class 'str'>]       19.98    80.02
1         genres  [<class 'float'>, <class 'str'>]       23.95    76.05
2       app_name  [<class 'float'>, <class 'str'>]       26.68    73.32
3          title  [<class 'float'>, <class 'str'>]       24.98    75.02
4            url  [<class 'float'>, <class 'str'>]       26.68    73.32
5   release_date  [<class 'float'>, <class 'str'>]       24.96    75.04
6           tags  [<class 'float'>, <class 'str'>]       26.54    73.46
7    reviews_url  [<class 'float'>, <class 'str'>]       26.68    73.32
8          specs  [<class 'float'>, <class 'str'>]       26.12    73.88
9          price  [<class 'float'>, <class 'str'>]       25.54    74.46
10  early_access                 [<class 'float'>]       26.68    73.32
11            id                 [<class 'float'>]       26.68    73.32
12     developer  [<class 'float'>, <class 'str'>]       23.94    76.06

* Ahora que he visualizado mis datasets voy entendiendolos poco a poco y hare una limpieza en mi df3, llamada 'output_games' borrando los datos_nulos.

In [42]:
df3.dropna(how='all', inplace=True)  # Eliminar filas con todos los valores nulos
df3.reset_index(drop=True, inplace=True)  # Restablecer los índices y eliminar el índice anterior

In [43]:
# Nuevamente he hecho una visualización a mi Dataframe y se ven algunos valores nulos
nulos = df3.isnull().sum()

print("Valores nulos por columna:")
print(nulos)

print("\nInformación del DataFrame:")
print(df3.info())

Valores nulos por columna:
publisher       8071
genres          3283
app_name           2
title           2050
url                0
release_date    2067
tags             163
reviews_url        2
specs            670
price           1377
early_access       0
id                 2
developer       3299
dtype: int64

Información del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32135 entries, 0 to 32134
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   publisher     24064 non-null  object
 1   genres        28852 non-null  object
 2   app_name      32133 non-null  object
 3   title         30085 non-null  object
 4   url           32135 non-null  object
 5   release_date  30068 non-null  object
 6   tags          31972 non-null  object
 7   reviews_url   32133 non-null  object
 8   specs         31465 non-null  object
 9   price         30758 non-null  object
 10  early_access  32135 non-null  float64
 11  id            32133 non-null  float64
 12  developer     28836 non-null  object
dtypes: float64(2), object(11)
memory usage: 3.2+ MB
None

In [44]:
# Comprobación del tamaño de mi  DataFrame 'output_games.csv' 
df3.shape

(32135, 13)

In [61]:
# Eliminare algunas columnas que se consideraron no relevantes.
columnas_a_eliminar = ['reviews_url', 'url', 'early_access', 'id']
df3 = df3.drop(columnas_a_eliminar, axis=1)

In [62]:
#Dado que aún se encontraban presentes algunos valores nulos en el DataFrame,
# opté por eliminarlos con el objetivo de optimizar su estructura y calidad.
df3 = df3.dropna()

In [63]:
nulos = df3.isnull().sum()

print("Valores nulos por columna:")
print(nulos)

Valores nulos por columna:
publisher       0
genres          0
app_name        0
title           0
release_date    0
tags            0
specs           0
price           0
developer       0
dtype: int64

In [64]:
#He generado un nuevo DataFrame
# que carece de valores nulos y está listo para ser utilizado en el Análisis Exploratorio de Datos (EDA).
df3.to_csv('steam_games.csv', index=False)

<p>El proceso anterior presentó un desafío en la tarea de desanidar los archivos, lo cual implicó una investigación detallada. Sin embargo, ahora los archivos están preparados y listos para hacerles una ultima revisión antes del siguiente paso, que es el Análisis Exploratorio de Datos (EDA). Finalmente, exportaré los datos a un nuevo archivo CSV para su utilización en la etapa subsiguiente.</p>

* Exportando los archivos que estaban anidados a CSV

In [61]:
df1_reviews_copia_3.to_csv('aus_reviews.csv', index=False)

In [60]:
df2_items_copia_3.to_csv('aus_items.csv', index=False)

In [3]:
# Leemos el Dataset que venimos trabajando en (ETL) ya modificado.
df_review= pd.read_csv('aus_reviews.csv')

In [4]:
df_review.head()

,user_id,user_url,funny,posted,last_edited,item_id,helpful,recommend,review
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,NaN,"Posted November 5, 2011.",NaN,1250,No ratings yet,True,Simple yet with great replayability. In my opi...
1,76561197970982479,http://steamcommunity.com/profiles/76561197970...,NaN,"Posted July 15, 2011.",NaN,22200,No ratings yet,True,It's unique and worth a playthrough.
2,76561197970982479,http://steamcommunity.com/profiles/76561197970...,NaN,"Posted April 21, 2011.",NaN,43110,No ratings yet,True,Great atmosphere. The gunplay can be a bit chu...
3,js41637,http://steamcommunity.com/id/js41637,NaN,"Posted June 24, 2014.",NaN,251610,15 of 20 people (75%) found this review helpful,True,I know what you think when you see this title ...
4,js41637,http://steamcommunity.com/id/js41637,NaN,"Posted September 8, 2013.",NaN,227300,0 of 1 people (0%) found this review helpful,True,For a simple (it's actually not all that simpl...

In [5]:
# He hecho una función para una inspección de datos e identificar valores nulos en todas las columnas.
# Esto nos ayudará a tomar decisiones adicionales sobre cómo manejar los valores faltantes.

def data_inspeccion(variables):
    print(f'Shape: {variables.shape}')
    print(f'\nDatos faltantes:')
    for columna in variables.columns:
        cantidad_nulos = df_review[columna].isnull().sum()
        print(f'{columna}: {cantidad_nulos} valores nulos')

data_inspeccion(df_review)

Shape: (59305, 9)

Datos faltantes:
user_id: 0 valores nulos
user_url: 0 valores nulos
funny: 51154 valores nulos
posted: 0 valores nulos
last_edited: 53165 valores nulos
item_id: 0 valores nulos
helpful: 0 valores nulos
recommend: 0 valores nulos
review: 30 valores nulos

In [6]:
# Elimine las filas con valores nulos 
df_review.dropna(inplace=True)

# Visualizó los valores nulos después de eliminar
data_inspeccion(df_review)

Shape: (1160, 9)

Datos faltantes:
user_id: 0 valores nulos
user_url: 0 valores nulos
funny: 0 valores nulos
posted: 0 valores nulos
last_edited: 0 valores nulos
item_id: 0 valores nulos
helpful: 0 valores nulos
recommend: 0 valores nulos
review: 0 valores nulos

In [7]:
df_review.head()

,user_id,user_url,funny,posted,last_edited,item_id,helpful,recommend,review
24,Wackky,http://steamcommunity.com/id/Wackky,1 person found this review funny,"Posted October 21, 2012.","Last edited November 25, 2013.",550,1 of 1 people (100%) found this review helpful,True,This game is fantastic if you are looking to D...
214,kevinator23,http://steamcommunity.com/id/kevinator23,1 person found this review funny,"Posted July 6, 2015.",Last edited March 8.,218620,2 of 5 people (40%) found this review helpful,True,"PayDay 2 on the difficulty scale -Normal - ""lo..."
239,Lord_Exploit,http://steamcommunity.com/id/Lord_Exploit,1 person found this review funny,"Posted March 13, 2015.","Last edited March 19, 2015.",311560,6 of 10 people (60%) found this review helpful,True,So after 30 odd hours i thought i'd write a re...
287,76561198141443390,http://steamcommunity.com/profiles/76561198141...,3 people found this review funny,"Posted May 3, 2015.","Last edited November 8, 2015.",730,3 of 4 people (75%) found this review helpful,True,Game is very fun and very enjoyable :)
301,2768820078,http://steamcommunity.com/id/2768820078,2 people found this review funny,Posted April 18.,Last edited April 23.,310950,2 of 3 people (67%) found this review helpful,True,‰∏∫‰∫Ü‰∏çÊéâlpÔºåÁé©Âà∞Âø´Ë¢´Âπ≤ÊéâÁöÑÊó∂ÂÄôÁ™...

In [8]:
# Eliminar columnas que no me son relevantes con el análisis.
reviews_drop = ["user_url", "posted", "last_edited"]
df_review.drop(columns=reviews_drop, inplace=True)

In [9]:
df_review.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1160 entries, 24 to 59281
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   user_id    1160 non-null   object
 1   funny      1160 non-null   object
 2   item_id    1160 non-null   int64
 3   helpful    1160 non-null   object
 4   recommend  1160 non-null   bool
 5   review     1160 non-null   object
dtypes: bool(1), int64(1), object(4)
memory usage: 55.5+ KB

In [10]:
# Ordenar el índice de manera ascendente
df_review = df_review.sort_index()

# Restablecer el índice para que los números estén en orden
df_review = df_review.reset_index(drop=True) # Esto evita que se agregue una columna adicional con el índice anterior.

df_review.head()

,user_id,funny,item_id,helpful,recommend,review
0,Wackky,1 person found this review funny,550,1 of 1 people (100%) found this review helpful,True,This game is fantastic if you are looking to D...
1,kevinator23,1 person found this review funny,218620,2 of 5 people (40%) found this review helpful,True,"PayDay 2 on the difficulty scale -Normal - ""lo..."
2,Lord_Exploit,1 person found this review funny,311560,6 of 10 people (60%) found this review helpful,True,So after 30 odd hours i thought i'd write a re...
3,76561198141443390,3 people found this review funny,730,3 of 4 people (75%) found this review helpful,True,Game is very fun and very enjoyable :)
4,2768820078,2 people found this review funny,310950,2 of 3 people (67%) found this review helpful,True,‰∏∫‰∫Ü‰∏çÊéâlpÔºåÁé©Âà∞Âø´Ë¢´Âπ≤ÊéâÁöÑÊó∂ÂÄôÁ™...

In [11]:
df_review.shape

(1160, 6)

* He observado que la columna 'review' presenta caracteres simbólicos en lugar de texto legible, lo cual podría conllevar a complicaciones durante el proceso de modelado.

In [12]:
columna = df_review['review'].head(50)
print(columna)

0     This game is fantastic if you are looking to D...
1     PayDay 2 on the difficulty scale -Normal - "lo...
2     So after 30 odd hours i thought i'd write a re...
3                Game is very fun and very enjoyable :)
4     ‰∏∫‰∫Ü‰∏çÊéâlpÔºåÁé©Âà∞Âø´Ë¢´Âπ≤ÊéâÁöÑÊó∂ÂÄôÁ™...
5     Great GameReasons why:1.  It Adds Challenge to...
6     +: Combines aspects from other games in a way ...
7     Fun Valve classic that challenges your team wo...
8                                                   Yes
9     In dis game yo ‚ô•‚ô•‚ô• be a Terrorist or eli...
10    Extremely TOXIC (horrible) "community", da mos...
11    I have nearly 2k hours played and I've spent n...
12    Dayz is a step up from the mod.it runs off it ...
13    It's a great game, but its dead; the only ones...
14    Although the long awaited update finally came ...
15    This game is so boring & repetitive, that it h...
16    ok if your thinking of playing this game don't...
17    I may only have 116 hours on rust however mayb...
18    Do you want A date with Palmela Handerson?Or l...
19    THIS GAME IS ‚ô•‚ô•‚ô•‚ô•ING AWFUL. DO NOT BUY...
20                                            No Bread.
21    this game is essentially another one of those ...
22    this is by far the greatest rpg i have played ...
23     pewdiepie played this game first‚ô•‚ô•‚ô•‚ô• off
24    it's free and pretty fun to play with friendsb...
25    I reccomend it! I got it when it was $55 and I...
26    I personally think War Thunder is a great game...
27    Great banter has been had while playing this g...
28    Please dont play this game, but if you do plea...
29                         Became a suicide bomber 9/11
30    Unlike its new sequel; Dark Souls 3, DS2 has d...
31    One black class in the game that throws bombs....
32    Named myself Justin BieberGot role veteranWent...
33    Made the mistake of leaving the Gas Station an...
34    Literally the best game ever made, the storyli...
35    This sucks more then Fan4stic, and that is say...
36    When you die you leave a crate behind with a ‚...
37                    The King Is Back Guys , Enjoy !!!
38    One of the best FPS games out there. For the v...
39    The McDonald‚Äôs we‚Äôve known for more than h...
40    is gud.can build heavy tank then destroy heavy...
41    I got killed by binoculars...10/10http://steam...
42                                  Orcs are pretty fun
43                                       Cup of noodles
44    Zombie children punch you in the balls and you...
45                                                   eh
46                                Need to do the banzai
47        Damn New Zealand didn't want Obama's promises
48    This game is good so here is a pancake recipe ...
49    This game has been an extremely big let down, ...
Name: review, dtype: object

In [13]:
def clean_text(text):
    # Este codigo utiliza una expresión regular para eliminar todo lo que no sea texto y espacios en blanco
    cleaned_text = re.sub(r'[^a-zA-Z\s]', '', text)
    return cleaned_text

# Aplicó la función a la columna 'review'
df_review['review'] = df_review['review'].apply(clean_text)

In [14]:
# Vuelvo a correr el mismo codigo para verificar si trabajo la función
columna = df_review['review'].head(50)
print(columna)

0     This game is fantastic if you are looking to D...
1     PayDay  on the difficulty scale Normal  lolwut...
2     So after  odd hours i thought id write a reaso...
3                  Game is very fun and very enjoyable
4                                               lphappy
5     Great GameReasons why  It Adds Challenge to th...
6      Combines aspects from other games in a way th...
7     Fun Valve classic that challenges your team wo...
8                                                   Yes
9     In dis game yo  be a Terrorist or elite Counte...
10    Extremely TOXIC horrible community da most thu...
11    I have nearly k hours played and Ive spent nea...
12    Dayz is a step up from the modit runs off it o...
13    Its a great game but its dead the only ones wh...
14    Although the long awaited update finally came ...
15    This game is so boring  repetitive that it hur...
16    ok if your thinking of playing this game dont ...
17    I may only have  hours on rust however maybe o...
18    Do you want A date with Palmela HandersonOr li...
19    THIS GAME IS ING AWFUL DO NOT BUYQuite simply ...
20                                             No Bread
21    this game is essentially another one of those ...
22    this is by far the greatest rpg i have played ...
23                 pewdiepie played this game first off
24    its free and pretty fun to play with friendsbu...
25    I reccomend it I got it when it was  and I sti...
26    I personally think War Thunder is a great game...
27    Great banter has been had while playing this g...
28    Please dont play this game but if you do pleas...
29                             Became a suicide bomber
30    Unlike its new sequel Dark Souls  DS has done ...
31    One black class in the game that throws bombsO...
32    Named myself Justin BieberGot role veteranWent...
33    Made the mistake of leaving the Gas Station an...
34    Literally the best game ever made the storylin...
35    This sucks more then Fanstic and that is sayin...
36    When you die you leave a crate behind with a  ...
37                        The King Is Back Guys  Enjoy
38    One of the best FPS games out there For the ve...
39    The McDonalds weve known for more than half a ...
40    is gudcan build heavy tank then destroy heavy ...
41    I got killed by binocularshttpsteamcommunityco...
42                                  Orcs are pretty fun
43                                       Cup of noodles
44    Zombie children punch you in the balls and you...
45                                                   eh
46                                Need to do the banzai
47          Damn New Zealand didnt want Obamas promises
48    This game is good so here is a pancake recipe ...
49    This game has been an extremely big let down t...
Name: review, dtype: object

### Ahora es el turno del Dataset 'items', para analizar su naturaleza y hacerle una limpieza, para el modelamiento.

In [15]:
df_items = pd.read_csv('aus_items.csv')
df_items.head()

,user_id,items_count,steam_id,user_url,item_id,item_name,playtime_forever,playtime_2weeks
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,10,Counter-Strike,6,0
1,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,20,Team Fortress Classic,0,0
2,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,30,Day of Defeat,7,0
3,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,40,Deathmatch Classic,0,0
4,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,50,Half-Life: Opposing Force,0,0

In [16]:
# Visualizó  la dimensión de mis datos 
df_items.shape

(5153209, 8)

In [17]:
# Elimino columnas que no me son relevantes con el análisis.
items_drop = ["steam_id","user_url"]
df_items.drop(columns=items_drop, inplace=True)

In [18]:
# Veo ahora si tiene datos faltantes,usando la misma función
# que utilice para df_reviews.

def data_inspeccion(variables):
    print(f'Shape: {variables.shape}')
    print(f'\nDatos faltantes:')
    for columna in variables.columns:
        cantidad_nulos = df_items[columna].isnull().sum()
        print(f'{columna}: {cantidad_nulos} valores nulos')

data_inspeccion(df_items)

Shape: (5153209, 6)

Datos faltantes:
user_id: 0 valores nulos
items_count: 0 valores nulos
item_id: 0 valores nulos
item_name: 0 valores nulos
playtime_forever: 0 valores nulos
playtime_2weeks: 0 valores nulos

In [19]:
# vere si tiene duplicados mis datos y los visualizare.

duplicados = df_items[df_items.duplicated()]
duplicados

,user_id,items_count,item_id,item_name,playtime_forever,playtime_2weeks
164294,Nikiad,109,20,Team Fortress Classic,5,0
164295,Nikiad,109,50,Half-Life: Opposing Force,0,0
164296,Nikiad,109,70,Half-Life,0,0
164297,Nikiad,109,130,Half-Life: Blue Shift,0,0
164298,Nikiad,109,220,Half-Life 2,198,0
...,...,...,...,...,...,...
4898223,76561198080057659,39,213670,South Park‚Ñ¢: The Stick of Truth‚Ñ¢,725,0
4898224,76561198080057659,39,221910,The Stanley Parable,53,0
4898225,76561198080057659,39,261030,The Walking Dead: Season Two,253,0
4898226,76561198080057659,39,273110,Counter-Strike Nexon: Zombies,0,0
4898227,76561198080057659,39,730,Counter-Strike: Global Offensive,0,0

In [20]:
# Efectivamente tiene duplicados voy a proceder a eliminarlos.
df_items = df_items.drop_duplicates()

In [21]:
# Vuelvo a verificar mis datos con el método duplicated y .any() si aun hay duplicados.
duplicados = df_items.duplicated().any()
print(f"¿Hay duplicados en el DataFrame? {duplicados}")

¿Hay duplicados en el DataFrame? False

<p>En mi Dataframe 'aus_items.csv' al igual que mi Dataframe 'aus_reviews.csv' contiene simbolos que podrian perjudicar en nuestro modelado, si bien puedes mirar arriba (cuando lo visualize) se pueden ver algunos simbolos, por lo que acontinuación los eliminare.</p>

In [26]:
def clean_text(text):
    # Este codigo utiliza una expresión regular para eliminar todo lo que no sea texto y espacios en blanco
    cleaned_text = re.sub(r'[^a-zA-Z\s]', '', text)
    return cleaned_text

# Aplicó la función a la columna 'item_name'
df_items['item_name'] = df_items['item_name'].apply(clean_text)

In [32]:
df_items.head(58000)

,user_id,items_count,item_id,item_name,playtime_forever,playtime_2weeks
0,76561197970982479,277,10,CounterStrike,6,0
1,76561197970982479,277,20,Team Fortress Classic,0,0
2,76561197970982479,277,30,Day of Defeat,7,0
3,76561197970982479,277,40,Deathmatch Classic,0,0
4,76561197970982479,277,50,HalfLife Opposing Force,0,0
...,...,...,...,...,...,...
57995,76561198095380303,68,282900,Hyperdimension Neptunia ReBirth,42,0
57996,76561198095380303,68,243930,Bound By Flame,110,0
57997,76561198095380303,68,233290,MURDERED SOUL SUSPECT,483,0
57998,76561198095380303,68,201810,Wolfenstein The New Order,455,0
57999,76561198095380303,68,297860,SplitSecond,232,0

* En el Dataframe 'steam_games.csv', voy a darle una nueva revisada para ver si contiene datos duplicados y posteriormente le hare la función para borrar los simbolos que podrian afectar cuando hagamos el EDA.

In [44]:
# Leyendo el Dataframe 'steam_games.csv'
games= pd.read_csv('steam_games.csv')

In [45]:
# vere si tiene duplicados mis datos y los visualizare.

duplicados = games[games.duplicated()]
duplicados

,publisher,genres,app_name,title,release_date,tags,specs,price,developer
10093,Bethesda Softworks,['Action'],Wolfenstein II: The New Colossus,Wolfenstein II: The New Colossus,2017-10-26,"['Action', 'FPS', 'Gore', 'Violent', 'Alternat...","['Single-player', 'Steam Achievements', 'Full ...",59.99,Machine Games
21481,"Warner Bros. Interactive Entertainment, Feral ...","['Action', 'Adventure']",Batman: Arkham City - Game of the Year Edition,Batman: Arkham City - Game of the Year Edition,2012-09-07,"['Action', 'Open World', 'Batman', 'Adventure'...","['Single-player', 'Steam Achievements', 'Steam...",19.99,"Rocksteady Studios,Feral Interactive (Mac)"

In [46]:
# Eliminare los duplicados del dataset.
games = games.drop_duplicates()

In [47]:
# Vuelvo a verificar mis datos con el método duplicated y .any()
duplicados = games.duplicated().any()
print(f"¿Hay duplicados en el DataFrame? {duplicados}")

¿Hay duplicados en el DataFrame? False

In [51]:
def clean_text(text):
    cleaned_text = re.sub(r'[^a-zA-Z\s]', '', text)
    return cleaned_text

# Columnas que voy a limpiar
columns_to_clean = ['genres', 'tags', 'specs', 'publisher', 'app_name', 'title', 'developer']

# Aplicó la función a las columnas especificadas
for column in columns_to_clean:
    games[column] = games[column].apply(clean_text)

In [52]:
games.head()

,publisher,genres,app_name,title,release_date,tags,specs,price,developer
0,Kotoshiro,Action Casual Indie Simulation Strategy,Lost Summoner Kitty,Lost Summoner Kitty,2018-01-04,Strategy Action Indie Casual Simulation,Singleplayer,4.99,Kotoshiro
1,Making Fun Inc,Free to Play Indie RPG Strategy,Ironbound,Ironbound,2018-01-04,Free to Play Strategy Indie RPG Card Game Trad...,Singleplayer Multiplayer Online MultiPlayer Cr...,Free To Play,Secret Level SRL
2,Poolianscom,Casual Free to Play Indie Simulation Sports,Real Pool D Poolians,Real Pool D Poolians,2017-07-24,Free to Play Simulation Sports Casual Indie Mu...,Singleplayer Multiplayer Online MultiPlayer In...,Free to Play,Poolianscom
3,,Action Adventure Casual,,,2017-12-07,Action Adventure Casual,Singleplayer,0.99,
4,Trickjump Games Ltd,Action Adventure Simulation,Battle Royale Trainer,Battle Royale Trainer,2018-01-04,Action Adventure Simulation FPS Shooter ThirdP...,Singleplayer Steam Achievements,3.99,Trickjump Games Ltd

In [55]:
# Quiero visualizar las columnas que contienen valores nulos o en blanco
columnas_sin_data = games.columns[games.isnull().any()].tolist()

# El for imprime las columnas con valores faltantes
for column in columnas_sin_data:
    missing_count = games[column].isnull().sum()
    print(f"Columna: {column}, Valores faltantes: {missing_count}")

In [57]:
games.isnull().any()

publisher       False
genres          False
app_name        False
title           False
release_date    False
tags            False
specs           False
price           False
developer       False
dtype: bool

* Despues de haber limpiado los Dataframe los transformare a unos nuevos csv.

In [35]:
df_items.to_csv('aus_items_EDA.csv', index=False)

In [36]:
df_review.to_csv('aus_reviews_EDA.csv', index=False)

In [58]:
games.to_csv('steam_games_EDA.csv', index=False)